name = "Gtk App"

[main]
language = "c"
src = ["gtk-hello.c"]
type = "executable"

[[main.deps]]
name = "gtk4"
use = "pkg-config"

[[main.deps]]
name = "pgvector"
uri = "https://github.com/pgvector/pgvector.git"
use = "git"

[py-math]
language = "c"
src = ["py-math.c"]
type = "static_lib"
